### PR TITLE
Add CircleCI config

### PR DESCRIPTION
**Pull request by mizabrik**
I can also suggest to make the following configuration tweaks:
1. Enable testing PRs from forks: in CircleCI project settings go to `Build Settings > Advanced settings` and switch `Build forked pull requests` on.
2. Require green build before merging: in GitHub project settings go to `Branches > Branch protection rules`, enable `Require status checks to pass before merging` and tick `ci/circleci: build` where needed.

### CODE REVIEW

**Comment by code-of-kpp** [comment]
Thanks, cap.

Why do you use junit format?

**Comment by mizabrik** [comment]
Nice display in `Test Summary` tab, indeed.

**Comment by code-of-kpp** [comment]
Well, XML is not for humans :) and you don't use it anyway.  Usually `pytest --verbose --showlocals --color=yes` is good enough. Use still can have this xml but you should mark it as an artifact. Another option is to `|tie` results to some file and keep this one as an artifact. The problem with latter is that it kind of don't work good with colors.

**Comment by ivasio** [comment]
When running the tests there are following warning messages after each async test invocation
`Task was destroyed but it is pending!
task: <Task pending coro=<RedisConnection._read_data() done, defined at .../async_python/myvenv/lib/python3.7/site-packages/aioredis-1.2.0-py3.7.egg/aioredis/connection.py:177> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f646e5353a8>()]> cb=[Future.set_result()]>`
Does anybody have an idea of what could cause these warnings?

**Comment by code-of-kpp** [comment]
@ivasio  I think that this should be in your PR with those tests. Hard to tell without looking at code. Usually this means that result of some coroutine wasn't used so when the loop was shut down the result was still there.

**Comment by code-of-kpp** [comment]
@mizabrik: Please parametrize the circle CI file to run against python3.5, python3.6 and pypy3. Also, please update the `pytest` call.
As for setup flag to install `pytest` the usual (almost standard) `[test]` notation should be used instead of `[dev]`.

**Pull request merged**
