### PR TITLE
Setup fix

### PR DESCRIPTION
**Pull request by ivasio**
There was a problem when installing the library : lua scripts weren't copied. Fixed it by adding MANIFEST.in

### CODE REVIEW

**Comment by code-of-kpp** [comment]
Actually, `package_data` should work and `Manifest.in` is considered either deprecated or harmful (as it breaks `package_data` and `data_files`).

**Comment by code-of-kpp** [comment]
Please, verify, that you use fresh `pip` version. It could be the case that files are been installed but resulting location is not something assumed in the code. 
Perhaps some `pkg_resources` magic is required.

**Comment by ivasio** [comment]
Actually it was all just a typo in the key of package_data dict

**Comment by code-of-kpp** [comment]
Please, rebase to master and leave only the last commit (`git pull && git rebase master -i`)

**Pull request merged**
